name: Trigger Website Generation and Pull

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

jobs:
  generate-and-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Call generate-website endpoint
        run: |
          curl --fail "https://smart-isolator.fly.dev/generate-website?token=${{ secrets.WEBSITE_TOKEN }}"

      - name: Checkout Pages repo
        uses: actions/checkout@v4
        with:
          repository: smart-isolator/smart-isolator.github.io
          token: ${{ secrets.GH_PAT }}
          path: site

      - name: Download website files from Fly.io
        run: |
          cd site
          for id in c00001_d001 c00002_d001 c00003_d001 c99999_d001; do
            # Save HTML in root folder (or per hive folder)
            curl -f "https://smart-isolator.fly.dev/static/index_${id}.html" -o index_${id}.html
      
            # Save SVG into images/ folder, without v001_ prefix
            curl -f "https://smart-isolator.fly.dev/static/images/${id}_1.svg" -o images/${id}_1.svg
          done

      - name: Commit & push to GitHub Pages
        run: |
          cd site
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Website update from Fly.io on $(date -u)" || echo "No changes to commit"
          git push
