name: Trigger Website Generation and Pull

on:
  schedule:
    - cron: '0 */1 * * *'  # hourlys
  workflow_dispatch:

jobs:
  generate-and-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Call generate-website endpoint
        run: |
          curl --fail "https://smart-isolator.fly.dev/generate-website?token=${{ secrets.WEBSITE_TOKEN }}"

      - name: Checkout Pages repo
        uses: actions/checkout@v4
        with:
          repository: smart-isolator/smart-isolator.github.io
          token: ${{ secrets.GH_PAT }}
          path: site

      - name: Download website files from Fly.io
        run: |
          cd site
          mkdir -p images
        
          for id in c00001_d001 c00001_d011 c00001_d021 c00001_d031 c00002_d001 c00003_d001 c99999_d001; do
            # Try to download HTML
            curl -f "https://smart-isolator.fly.dev/static/index_${id}.html" -o index_${id}.html || true
        
            # Try to download SVG
            curl -f "https://smart-isolator.fly.dev/static/images/${id}_1.svg" -o images/${id}_1.svg || true
            curl -f "https://smart-isolator.fly.dev/static/images/${id}_2.svg" -o images/${id}_2.svg || true
            curl -f "https://smart-isolator.fly.dev/static/images/${id}_3.svg" -o images/${id}_3.svg || true
            curl -f "https://smart-isolator.fly.dev/static/images/${id}_4.svg" -o images/${id}_4.svg || true
            curl -f "https://smart-isolator.fly.dev/static/images/${id}_5.svg" -o images/${id}_5.svg || true
            curl -f "https://smart-isolator.fly.dev/static/images/${id}_6.svg" -o images/${id}_6.svg || true

            # JPGs from downloaded_images folder (added on Fly)
            curl -f "https://smart-isolator.fly.dev/static/downloaded_images/${id}_1.jpg" -o images/${id}_1.jpg || true
            curl -f "https://smart-isolator.fly.dev/static/downloaded_images/${id}_2.jpg" -o images/${id}_2.jpg || true
            curl -f "https://smart-isolator.fly.dev/static/downloaded_images/${id}_3.jpg" -o images/${id}_3.jpg || true
            curl -f "https://smart-isolator.fly.dev/static/downloaded_images/${id}_4.jpg" -o images/${id}_4.jpg || true
            curl -f "https://smart-isolator.fly.dev/static/downloaded_images/${id}_5.jpg" -o images/${id}_5.jpg || true

          done

      - name: Commit & push to GitHub Pages
        run: |
          cd site
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Website update from Fly.io on $(date -u)" || echo "No changes to commit"
          git push
